title: Kim MokJong
description: Front-End Engineer
site_title: 'Kim MokJong'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: rlaahrwhd
blog_url: 
email: rlaahrwhd@naver.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 